### ISSUE TITLE
Epic - TFExplorer v0.5.1 improvements

### ISSUE THREAD

**Issue by sasha-astiadi** [threefoldtech/tfexplorer#322]
Generic improvements on tfexplorer v0.5.1

#### User stories

- [x] Create UI feature to show of whether a node/farm is on grid 3 farming or not #314 

- [x] support filtering workloads by workload type #320 

- [x] ip4: atomic IPv4 transfer to another node #318
